import textwrap

from advent_of_code.year_2024 import day_08


class TestSolution:
    __PUZZLE_INPUT = textwrap.dedent("""\
        ............
        ........0...
        .....0......
        .......0....
        ....0.......
        ......A.....
        ............
        ............
        ........A...
        .........A..
        ............
        ............
    """)

    def test_part_1(self) -> None:
        assert day_08.solve_part_1(self.__PUZZLE_INPUT) == 14

    def test_part_2(self) -> None:
        assert day_08.solve_part_2(self.__PUZZLE_INPUT) == 34
